name: '_prop_action_server_name_ Action'
description: 'Execute _prop_action_server_name_ Test from GitHub Action'
inputs:
  serverUrl:
    description: '_prop_action_server_name_ URL'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
